image: python:3.9

default:
  tags:
    - docker

stages:
  - Static Analysis
  - tests

pylint:
  stage: Static Analysis
  script:
    - pip install -U pylint
    - pylint src/haikus
    
flake8:
  stage: Static Analysis
  script:
    - pip install -U flake8
    - flake8 ./src/haikus

pytest:
  stage: tests
  script:
    - pip install -U pytest
    - pytest --junitxml=report.xml tests
  artifacts:
    when: always
    reports:
      junit: report.xml
